# Site settings
title: XingJunJie's blog
email:
description: "Senior student at SJTU."
baseurl: ""
url: "http://gavinxing.github.io"
# twitter_username:
github_username:  gavinxing

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
